---
title: "Data Profile"
format: dashboard
server: shiny
theme: sandstone
---

# Score

## Row

### Column {width="25%"}

#### Row {height="40%"}

```{r}
x <- c(unique(as.character(datafiles$file_class)))
checkboxGroupInput("include_class", "Include File Class:", x, x, inline=TRUE)
```

#### Row {height="15%"}

```{r}
# https://icons.getbootstrap.com/
value_box(
  title = "Mean Score:",
  value = textOutput("score_card"),
  showcase_layout = "left center",
  theme = "info"
)
```

#### Row {height="45%"}

```{r}
#| fig.width: 6
#| fig.height: 6
#| title: "Mean Scores"

plotOutput("hist_scores")
```

### Column {width="75%"}

#### {height="70%"}

```{r}
#| fig.width: 6
#| fig.height: 6
#| title: "Mean Score by Metric"

plotOutput("radar")
```

```{r}
#| fig.width: 6
#| fig.height: 6
#| title: "Data Profile Scores"

plotOutput("ridges")
```

#### {height="30%"}

```{r}
span(tableOutput("scores"), style="font-size:12px")
```

```{r}
#| context: server

df_x <- reactive({
  x <- df
  x <- x[x$file_class %in% input$include_class, ]
  return(x)
})

n <- reactive({
  x <- df_x()
  flds <- c("accessibility", "completeness", "complexity",
            "consistency","metadata", "skewness", "uniqueness", "usability")
  x <- sapply(x[, flds], mean, na.rm=TRUE)
  x <- signif(100 * mean(x), 3)
  return(x)
})

output$score_card <- renderText({ n() })

output$hist_scores <- renderPlot({
  x <- df_x()
  ggplot(x, aes(x=score)) +
    geom_histogram()
})

output$box_scores <- renderPlot({
  x <- df_x()
  ggplot(x, aes(x=score)) +
    geom_boxplot()
})

output$radar <- renderPlot({
  x <- c("accessibility", "completeness", "complexity", "consistency",
        "metadata", "skewness", "uniqueness", "usability")
  x <- sapply(df_x()[, x], mean, na.rm=TRUE)
  x <- c(mean(x), x)
  x <- t(data.frame(score = x))
  ggradar(x, plot.extent.x.sf=1.2, plot.extent.y.sf=1.2, group.point.size=2)
})

output$ridges <- renderPlot({
  x <- df_x()[, c("accessibility","metadata","completeness",
                  "complexity","consistency","skewness","uniqueness",
                  "usability")] |>
  stack()
  ggplot(x, aes(x=values, y=ind, fill = ..x..)) +
    geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
    scale_fill_viridis(option = "C") +
    xlab("score") +
    ylab("") +
    theme(legend.position="none",
          panel.spacing = unit(0.1, "lines"),
          strip.text.x = element_text(size = 8))
})

output$scores <- renderTable({
  x <- df_x() |>
    dplyr::select(all_of(c("file_name","file_ext","sheet_name","score",
                           "accessibility","metadata","completeness",
                           "complexity","consistency","skewness",
                           "uniqueness","usability"))) |>
    dplyr::arrange(score)
  return(x)
})
```
